name: Release Develop

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**/*'
      - default.project.json
      - mantle.yaml
      - package.json
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: development_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js 20
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --prod

      - name: Install roblox-ts
        run: pnpm add roblox-ts

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@a13c97e4a1f72bc90e106bf044118fea3e341ffb # v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: npx rbxtsc --verbose

      - name: Build project
        run: rojo build ./default.project.json --output place.rbxlx

      - name: Upload place
        uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4
        with:
          name: place
          path: place.rbxlx
          if-no-files-found: error
